name: build-v1

on:
  schedule:
    - cron: '10 4 * * 0' # Sundays at 4:10am

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "v1.1.0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build images
        run: |
          docker build \
            --tag syphr/webtts:1.1.0 \
            --tag syphr/webtts:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            .
      - name: Cleanup
        run: rm -f ${HOME}/.docker/config.json
