name: build-images

on:
  schedule:
    - cron: '0 4 * * *' # everyday at 4am
  push:
    branches:
      - master

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: "v1.0.0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build images
        run: |
          docker build \
            --tag syphr/webtts:1.0.0 \
            --tag syphr/webtts:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            .
      - name: Cleanup
        run: rm -f ${HOME}/.docker/config.json
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build images
        run: |
          docker build \
            --tag syphr/webtts:dev \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            .
      - name: Cleanup
        run: rm -f ${HOME}/.docker/config.json
